
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

string text = Console.ReadLine();

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new()
{
    Text = text,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine($"Predicted IsRacist: {predictionResult.PredictedLabel}");
Console.WriteLine($"Predicted IsRacist: {predictionResult.Score}");
Console.ReadKey();

