
// This file was auto-generated by ML.NET Model Builder. 
using MLModel1_ConsoleApp2;
using System.Security.Cryptography.X509Certificates;

Console.Write("Image path: ");
// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(Console.ReadLine());

ModelInput sampleData = new()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = MLModel1.Predict(sampleData);
var score = predictionResult.Score.OrderByDescending(x => x).ToList();
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel}");
List<string> directories = new DirectoryInfo(@"C:\Users\Admin\Downloads\archive(5)").GetDirectories().Select(x => x.Name).ToList();
List<KeyValuePair<string, float>> values = new();

for (int i = 0; i < directories.Count; i++)
{
    values.Add(KeyValuePair.Create(directories[i], score[i]));
}

foreach (var item in values)
{
    Console.WriteLine($@"{Math.Round(item.Value * 100, 2)}%");
}
